<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SocialAuthDoctrineORM\Entity\UserProvider'               => __DIR__ . '/src/SocialAuthDoctrineORM/Entity/UserProvider.php',
    'SocialAuthDoctrineORM\Options\ModuleOptions'             => __DIR__ . '/src/SocialAuthDoctrineORM/Options/ModuleOptions.php',
    'SocialAuthDoctrineORM\Service\UserProviderMapperFactory' => __DIR__ . '/src/SocialAuthDoctrineORM/Service/UserProviderMapperFactory.php',
    'SocialAuthDoctrineORM\Service\ModuleOptionsFactory'      => __DIR__ . '/src/SocialAuthDoctrineORM/Service/ModuleOptionsFactory.php',
    'SocialAuthDoctrineORM\Module'                            => __DIR__ . '/src/SocialAuthDoctrineORM/Module.php',
    'SocialAuthDoctrineORM\Mapper\UserProvider'               => __DIR__ . '/src/SocialAuthDoctrineORM/Mapper/UserProvider.php',
);